// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PointRepository is an autogenerated mock type for the PointRepository type
type PointRepository struct {
	mock.Mock
}

// DecreaseBronzePoint provides a mock function with given fields: ctx
func (_m *PointRepository) DecreaseBronzePoint(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseBronzePoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecreaseGoldPoint provides a mock function with given fields: ctx
func (_m *PointRepository) DecreaseGoldPoint(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseGoldPoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecreaseSilverPoint provides a mock function with given fields: ctx
func (_m *PointRepository) DecreaseSilverPoint(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseSilverPoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPointRepository creates a new instance of PointRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPointRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PointRepository {
	mock := &PointRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
